### Create Region
POST localhost:8080/api/v1/region/create
Authorization: Beare eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5Njg4NzMsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwNTUyNzQsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.jwL7m268dSoNn0p0YkGAeU0WMK9bWf8XM8zk_SmRE1wYOu5CSC6NH0FK8L1hstG7FeB24Qcz2LsxiD09TXMccg
Content-Type:  application/json

{
  "nameUz": "sddgf",
  "nameRu": "dsgfd",
  "nameEn": "sfdg"
}

### Update article type
POST localhost:8080/api/v1/region/update/3
Authorization: Beare eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5Njg4NzMsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwNTUyNzQsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.jwL7m268dSoNn0p0YkGAeU0WMK9bWf8XM8zk_SmRE1wYOu5CSC6NH0FK8L1hstG7FeB24Qcz2LsxiD09TXMccg
Content-Type:  application/json

{
  "nameUz": "boy",
  "nameRu": "богатый",
  "nameEn": "rich"
}

### delete region
GET localhost:8080/api/v1/region/delete/2
Authorization: Beare eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5Njg4NzMsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwNTUyNzQsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.jwL7m268dSoNn0p0YkGAeU0WMK9bWf8XM8zk_SmRE1wYOu5CSC6NH0FK8L1hstG7FeB24Qcz2LsxiD09TXMccg


### pagination region
PUT localhost:8080/api/v1/region/paging
Authorization: Beare eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5Njg4NzMsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwNTUyNzQsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.jwL7m268dSoNn0p0YkGAeU0WMK9bWf8XM8zk_SmRE1wYOu5CSC6NH0FK8L1hstG7FeB24Qcz2LsxiD09TXMccg


### get lang region
GET localhost:8080/api/v1/region/getLang/en
