### Create Region
POST localhost:8080/api/v1/region/create
Authorization: Beare eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzMjA5NzksImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODM0MDczNzksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.tmhkxOuY7YNNRg3-wW8lVlK2yQA5UGG-PeqFuqzyx85MC_yAd2RkktzKgc8C5GCEQEAxcth05FxAyr92szEVhQ
Content-Type:  application/json

{
  "nameUz": "sddgf",
  "nameRu": "dsgfd",
  "nameEn": "sfdg"
}

### Update region
POST localhost:8080/api/v1/region/update/3
Authorization: Beare eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzMjA5NzksImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODM0MDczNzksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.tmhkxOuY7YNNRg3-wW8lVlK2yQA5UGG-PeqFuqzyx85MC_yAd2RkktzKgc8C5GCEQEAxcth05FxAyr92szEVhQ
Content-Type:  application/json

{
  "nameUz": "boy",
  "nameRu": "богатый",
  "nameEn": "rich"
}

### delete region
GET localhost:8080/api/v1/region/delete/2
Authorization: Beare eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzMjA5NzksImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODM0MDczNzksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.tmhkxOuY7YNNRg3-wW8lVlK2yQA5UGG-PeqFuqzyx85MC_yAd2RkktzKgc8C5GCEQEAxcth05FxAyr92szEVhQ


### pagination region
PUT localhost:8080/api/v1/region/paging
Authorization: Beare eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzMjA5NzksImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODM0MDczNzksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.tmhkxOuY7YNNRg3-wW8lVlK2yQA5UGG-PeqFuqzyx85MC_yAd2RkktzKgc8C5GCEQEAxcth05FxAyr92szEVhQ


### get lang region
GET localhost:8080/api/v1/region/getLang/en
